version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
    labels:
      - dependencies
    rebase-strategy: auto

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix"
      prefix-development: "build"
      include: "scope"
    labels:
      - dependencies
    rebase-strategy: auto
